export const errorCode = {
  NOT_FOUND: "NOT_FOUND",
  INVALID: "INVALID",
  CONNECTION: "CONNECTION",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
} as const;

export const roles = {
  ADMIN: "ADMIN",
  USER: "USER",
} as const;
